# 專案名稱
name = "happy-feet-inn-api"

# 告訴 Cloudflare Pages 前端靜態檔案的輸出目錄是 "public"
pages_build_output_dir = "public"

# 相容性日期，確保環境穩定
compatibility_date = "2024-06-20"

# 綁定 KV 命名空間
[[kv_namespaces]]
binding = "ROOMS_KV"
id = "26a24683515742918824143a50d753c8"

# 設定環境變數
[vars]
GOOGLE_SHEET_ID = "1MOFcdTXg7x1NK-yaYoHHoHwC6NWGbWF4K64wNUmdD1w"
# GCP_SERVICE_ACCOUNT_KEY 是一個 secret，我們會在 Cloudflare 儀表板設定